spring:
  application:
    name: tpjad_project_backend
  datasource:
      url: jdbc:postgresql://localhost:5432/tpjad_project
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: confirmation.abc.zzz@gmail.com
    password: uzpkjuklqoplxyvt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
